In [2]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [7]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [8]:
A = np.random.randn(10)

In [9]:
A

array([-0.6558589 , -0.51953745, -0.394076  , -1.92057427, -0.72016754,
       -0.61469419, -0.31639744, -0.966968  , -1.37242986, -1.05335167])

In [10]:
B = np.random.randn(10)

In [11]:
B

array([ 0.73422564, -1.14639823, -0.68057724,  0.02981964,  0.48315872,
        2.06604252,  1.50411371,  1.17280397, -0.20551954, -0.10354319])

In [12]:
np.add(A,B)

array([ 0.07836674, -1.66593568, -1.07465324, -1.89075463, -0.23700883,
        1.45134833,  1.18771627,  0.20583598, -1.5779494 , -1.15689486])

In [13]:
np.maximum(A,B)

array([ 0.73422564, -0.51953745, -0.394076  ,  0.02981964,  0.48315872,
        2.06604252,  1.50411371,  1.17280397, -0.20551954, -0.10354319])